### ISSUE TITLE
Add setup task for full uds-core and allow default, up to date, version of uds-core/core-istio to be overridden with a variable

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-common#53]
There should be a setup task for deploying full uds-core in addition to core-istio as for some jobs either will be needed.

By default we want the setup task to deploy the latest version, but should have the capability for someone to override that if they are working to get their dependent project up to date or need to test against an older version for some reason. 

```[tasklist]
### Tasks
- [x] Add task to deploy full uds-core
- [x] Add inputs to both the uds-core and core-istio tasks for the uds-core version
- [x] Move the version to a default variable, along with the renovate comment to trigger updates
- [x] Add note to the documentation about how to specify a certain version of uds-core or core-istio
```

**Comment by mjnagel** [comment]
> By default we want the setup task to deploy the latest version, but should have the capability for someone to override that if they are working to get their dependent project up to date or need to test against an older version for some reason.

Not totally opposed to this, but I think there's some value in forcing people to use "latest" if they are consuming the latest uds-common tasks. It should encourage better behaviors around staying up to date, and there's still options if they want an older version (use an older uds-common or a local task). I think if we added it as an input we would need to be careful to ensure its tracked with renovate, otherwise this becomes one of those things that people just hit an issue with updates and leave it pinned. Ideally we could do that as part of the common renovate config - but I'm not sure how easy that would be to identify generically 🤔. The other concern I'd have... we don't expose any similar var for uds-cli version, and there's potential for those two to be coupled/dependent.

Just some food for thought - I can understand the desire for flexibility but trying to weigh that against encouraging good patterns/updating these dependencies, and simplifying that for the end user. But definitely want to hear other opinions - I'm not the main one consuming this workflow so curious on the end-user perspective.

**Comment by zachariahmiller** [comment]
Problem is that's unrealistic if there are multiple changes in a couple days that could be breaking. These tasks are meant flexible and reusable for most use cases, not force people to have to reprioritize something that may be a priority for them. 

Also maybe something breaks in uds-core but a release here also had a needed change for a task that is blocking other work that needs to be done. This is only intended as an escape hatch to temporarily avoid maddening problems that could impact certain teams differently.

The inspiration for this issue is when I had to update the common tasks and ended up having to by way of that jump several uds-core versions at once because 1. There wasn't a release of uds-core for each version represented here and 2. because the versions that had been in use in the swf package repos were on like version 1.2 I ended up having to manually copy these and edit things to test UDS version by version and it was a pretty horrible experience.

I would alternatively consider it acceptable for every UDS version or task change to correspond to their own patch release here and not group anything together but that adds additional maintenance overhead to this repo.

**Comment by mjnagel** [comment]
Thanks @zachariahmiller , that's good perspective. I was looking at it from the wrong lens. This makes a lot of sense to enable dev testing/unblocking CI. 

My hope would be that this is primarily used to unblock things and not a long-term solution, and that renovate is used to track the core version, but that should probably be left to the repo owners to decide rather than forcing at this level. :shipit:

**Comment by zachariahmiller** [comment]
> Thanks @zachariahmiller , that's good perspective. I was looking at it from the wrong lens. This makes a lot of sense to enable dev testing/unblocking CI. 
> 
> My hope would be that this is primarily used to unblock things and not a long-term solution, and that renovate is used to track the core version, but that should probably be left to the individual package owners to decide rather than forcing at this level. :shipit: 

♥️ Totally agree. Latest core version should always be the default in the common tasks and managed by renovate. The intent behind allowing the ability to override the version via input in a given package repo would be as a temporary, stop gap, measure to prevent blockers or overcome unforeseen issues, not for folks to adopt using it as a pattern.

**Comment by zachariahmiller** [comment]
Just an update on this ticket. As of i think 0.17.0 k3d-core-istio is now k3d-core-slim-dev and includes keycloak. Otherwise scope of this issue is still the same.
