### ISSUE TITLE
Create and Deploy Tasks should have an input variables for the path (and config where applicable) instead of a hardcoded path.

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-common#54]
Currently the create and deploy tasks assume zarf package in root and bundle under ./bundle. This is very limiting. 

For example, certain packages have helper packages for dev/test that do not live in the root of the repository and as such a separate task needs to be created to build them.

Additionally, certain repos will have multiple bundles that need to be tested which will live in different repos. 

This could be accomplished with putting a path and input in a `dir:` on the tasks but that impacts the flow of things by not having everything run relative to the repo root. A more consistent solution is to have an input with a default that is added to the tasks command. 

Additionally, in the case of a bundle, the name of the uds-config.yaml should be overridable so if needed multiple config files can be run against the same bundle.

For example:

The bundle [deploy task](https://github.com/defenseunicorns/uds-common/blob/fc12e3a773580020a1d63e254525eab0f8b99fc8/tasks/deploy.yaml#L13) can be modified like so:

```yaml
  - name: test-bundle
    inputs:
      path:
        description: "Path relative to the repositories root where the uds-bundle.yaml lives"
        default: bundle
      config:
        description: "File name of the bundle config file. Defaults to uds-config.yaml. Path is relative to the path input."
        default: uds-config.yaml
    actions:
      - description: Deploy the UDS bundle with the package and its dependencies
        cmd: UDS_CONFIG=${{ .inputs.path }}/${{ .inputs.config }} uds deploy ${{ .inputs.path }}/uds-bundle-*-${UDS_ARCH}-*.tar.zst --confirm --no-progress
```

```[tasklist]
### Tasks
- [ ] Update bundle create task
- [ ] update Bundle Deploy Task
- [ ] Update zarf package create task
- [ ] Update zarf package deploy task
```
Note: [SWF](https://github.com/defenseunicorns/uds-software-factory/) will require this for bundles. [UDS Core](https://github.com/defenseunicorns/uds-core) should be able to use both the bundle and package tasks after these changes are made

**Comment by zachariahmiller** [comment]
@naveensrinivasan It looks like what you did for bundles in your PR should work. Here is an example of what i would expect the zarf package create and deploy tasks to look like when updated 

```yaml
  - name: package
    description: Create the UDS Zarf Package
    inputs:
      options:
        description: For setting create time variables and flags
      path:
        description: path of built zarf package to deploy
        default: ""
    actions:
      - cmd: uds zarf package create ${{ .inputs.path }} --confirm --no-progress --architecture=${UDS_ARCH} --flavor ${FLAVOR} ${{ .inputs.options }}
```

Similar for the deploy step. These should be analogous to the bundle ones you just did, but without the UDS_CONFIG=uds-config.yaml piece as we arent currently doing that with zarf yamls at the moment and dont want to add scope.

Disclaimer: that is a mock up. I have not tested this locally. It should work or be very close to working but please verify locally.
